version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres:/postgres_data/
          # copy the sql script to create tables
          - ./scripts/dbd_tables.sql:/docker-entrypoint-initdb.d/dbd_tables.sql
          # copy the sql script to create triggers
          - ./scripts/dbd_trigger.sql:/docker-entrypoint-initdb.d/dbd_trigger.sql
          # copy the sql script to create views
          - ./scripts/dbd_views.sql:/docker-entrypoint-initdb.d/dbd_views.sql
          # copy the sql script to create procedures
          - ./scripts/dbd_stored_procedures.sql:/docker-entrypoint-initdb.d/dbd_stored_procedures.sql
          # copy the sql script to fill tables
          #- ./scripts/dbd_input.sql:/docker-entrypoint-initdb.d/dbd_input.sql
